name: Format code
on: [push, pull_request]

jobs:
    format-code:
        name: Format code
        runs-on: ubuntu-latest
        if: always()
        steps:
            - name: Checkout to branch
              uses: actions/checkout@v2
            - name: Format code
              run: yarn check-format || echo FAIL
