name: Format code
on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    format-code:
        name: Format code
        runs-on: ubuntu-latest
        steps:
            - name: Checkout to branch
              uses: actions/checkout@v2
            - name: Format code
              run: yarn check-format
              continue-on-error: true
            - name: Echo
              if: failure()
              run: echo SUCCESS; exit 0;
