name: Format code
on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    format-code:
        name: Format code
        runs-on: ubuntu-latest
        steps:
            - name: Checkout to branch
              uses: actions/checkout@v2

            - name: Format code
              id: check
              run: yarn check-format
              continue-on-error: true

            - name: Format code
              if: steps.check.outcome != 'success'
              id: cpr
              uses: peter-evans/create-pull-request@v3
              with:
                  commit-message: "Prettified Code!"
                  branch: format-code
                  delete-branch: true
                  title: "Code Prettified"
                  body: "Code files formatted using prettier"
                  labels: code-format
                  reviewers: Muhammed-Rahif
                  milestone: 1
