name: "Prevent heroku sleep"

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  prevent-sleep:
    name: Prevent heroku sleep
    runs-on: ubuntu-latest
    steps:
      - name: Send a get request to server
        run: curl -X GET https://beomax.herokuapp.com/api/v1/stars
