name: Run jest tests
on: [push, pull_request, workflow_dispatch]
jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn build
    - name: Run tests
      run: yarn test
        
