name: Run jest tests
on: [push, pull_request, workflow_dispatch]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 16.13.0
    - run: yarn build 
    - run: yarn test
    - uses: mattallty/jest-github-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # with:
        # test-command: "yarn test"
        
